/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package Piavca;

public class PiavcaBase {
  public static boolean checkNaN(Vec v) {
    return PiavcaBaseJNI.checkNaN__SWIG_0(Vec.getCPtr(v), v);
  }

  public static Quat slerp(Quat q1, Quat q2, float t) {
    return new Quat(PiavcaBaseJNI.slerp(Quat.getCPtr(q1), q1, Quat.getCPtr(q2), q2, t), true);
  }

  public static boolean checkNaN(Bound v) {
    return PiavcaBaseJNI.checkNaN__SWIG_1(Bound.getCPtr(v), v);
  }

  public static SWIGTYPE_p_std__wstring StringToWString(String str) {
    return new SWIGTYPE_p_std__wstring(PiavcaBaseJNI.StringToWString(str), true);
  }

  public static String WStringToString(SWIGTYPE_p_std__wstring str) {
    return PiavcaBaseJNI.WStringToString(SWIGTYPE_p_std__wstring.getCPtr(str));
  }

  public static KeyframeMotion copyMotionPosture(Motion mot, float time) {
    long cPtr = PiavcaBaseJNI.copyMotionPosture(Motion.getCPtr(mot), mot, time);
    return (cPtr == 0) ? null : new KeyframeMotion(cPtr, false);
  }

  public static float getPi() {
    return PiavcaBaseJNI.Pi_get();
  }

  public static float degToRad(float angle) {
    return PiavcaBaseJNI.degToRad(angle);
  }

  public static float radToDeg(float angle) {
    return PiavcaBaseJNI.radToDeg(angle);
  }

}
